### ISSUE TITLE
Create sample Character

### ISSUE THREAD

**Issue by RickyNM** [RickyNM/TableTopRPGToolbox#10]
Make a sample character to show how we will store the data.

**Comment by StriderJonak** [comment]
<h1> Character Overview </h1>
A character is an an object with multiple properties that can be referenced by the TTRPGToolbox.
<h2> Currently defined Character properties </h2>
- Name
- Race
- Class
- Background
- Stats
- Inventory

**Comment by StriderJonak** [comment]
## Example Character

### General
Player: Strider Jonak
Name: Raye Penbar
Race: Human
Class: Theif
Background: Charlatan

### Statistics
16/20 HP
13 AC
30 Speed
250 EXP

### Lists
Items: Rapier, Dagger
Spells: Viscious Mockery

**Comment by StriderJonak** [comment]
## Example Alive

### General
Name: Gandalf the Gray
Alignment: Chaotic-Neutral

### Statistics
Health: 10/10 + 0  (Current/Max + Temporary)
Stats: [9,18,12,13,12,16] (6 elements)
Mods: [-1,4,1,2,1,3] (6 elements)
Pros: [false....true] (18 elements)
Armor: 8
Speed: 30
EXP: 500

### Lists
Items: Rapier, Dagger
Spells: Vicious Mockery
