### ISSUE TITLE
Review & Merge Policy

### ISSUE THREAD

**Issue by RickyNM** [RickyNM/TableTopRPGToolbox#16]
Having done work on the project now I think that it would be a good idea for us to submit a pull request to merge our work before our meetings. I would purpose we do this by having everyone assigned to someone else and each of us handles merging the work of whoever is assigned to us. This makes it so that we can all see the changes that each of us are making outside of our meetings and makes sure that someone is going over all of the suggested changes. Please think about this and post your opinion on the matter as a comment to this issue.

**Comment by JarrettAzar** [comment]
Strider review Sam
Jarrett Review Ricky
Sam Review Jarrett
Ricky review Strider
