### ISSUE TITLE
Find out how to get code from another repository

### ISSUE THREAD

**Issue by RickyNM** [RickyNM/TableTopRPGToolbox#8]
Please find out how to use code from another repository. Here is one that is a random name generator, https://github.com/Valkryst/VNameGenerator . Here is a list for map generators, https://github.com/jmecn/MapGenerator/tree/master/MapGenerator .

**Comment by JarrettAzar** [comment]
1. Download full project.
2. Use command line to "clone" the repository to ours or the test repository.
